import { useEffect, useMemo, useState } from 'react'
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { supabase } from './lib/supabase'

type Status = 'draft' | 'live' | 'closed'
type PollType = 'choice' | 'qa'
type Poll = { id: string; title: string; question: string; type: PollType; status: Status; created_at: string }
type Option = { id: string; poll_id: string; option_text: string; display_order: number }
type Vote = { id: string; poll_id: string; option_id: string; created_at: string }
type Question = { id: string; poll_id: string; question_text: string; upvotes: number; created_at: string }

const colors = ['#6d5dfc','#10b981','#f59e0b','#ec4899','#06b6d4','#8b5cf6']
const statusLabel: Record<Status, string> = { draft: 'Draft', live: 'Live', closed: 'Closed' }

function usePoll(id?: string) {
  const [poll, setPoll] = useState<Poll | null>(null); const [options, setOptions] = useState<Option[]>([]); const [votes, setVotes] = useState<Vote[]>([]); const [questions, setQuestions] = useState<Question[]>([]); const [loading, setLoading] = useState(true)
  const load = async () => { if (!id) return; setLoading(true); const [p,o,v,q] = await Promise.all([supabase.from('polls').select('*').eq('id',id).single(),supabase.from('options').select('*').eq('poll_id',id).order('display_order'),supabase.from('votes').select('*').eq('poll_id',id),supabase.from('questions').select('*').eq('poll_id',id).order('upvotes',{ascending:false})]); setPoll(p.data); setOptions(o.data ?? []); setVotes(v.data ?? []); setQuestions(q.data ?? []); setLoading(false) }
  useEffect(() => { load(); if (!id) return; const channel=supabase.channel(`poll-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'polls',filter:`id=eq.${id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'options',filter:`poll_id=eq.${id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'votes',filter:`poll_id=eq.${id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'questions',filter:`poll_id=eq.${id}`},load).subscribe(); return ()=>{supabase.removeChannel(channel)} },[id])
  return {poll,options,votes,questions,loading,reload:load}
}

function Shell({children}:{children:React.ReactNode}) { return <><header><Link to="/" className="brand"><span>◉</span> PulseLive</Link><nav><Link to="/">Dashboard</Link><Link to="/create" className="button small">Create poll</Link></nav></header><main>{children}</main></> }
function Badge({status}:{status:Status}) { return <span className={`badge ${status}`}>{statusLabel[status]}</span> }
function Loading(){return <div className="state">Loading PulseLive…</div>}

function Dashboard(){ const [polls,setPolls]=useState<Poll[]>([]); const [counts,setCounts]=useState<Record<string,number>>({}); const [loading,setLoading]=useState(true); useEffect(()=>{(async()=>{const {data}=await supabase.from('polls').select('*').order('created_at',{ascending:false}); const entries=await Promise.all((data??[]).map(async p=>{const {count}=await supabase.from(p.type==='choice'?'votes':'questions').select('*',{count:'exact',head:true}).eq('poll_id',p.id);return[p.id,count??0] as const}));setPolls(data??[]);setCounts(Object.fromEntries(entries));setLoading(false)})()},[]); return <Shell><section className="page-head"><div><p className="eyebrow">PRESENTER SPACE</p><h1>Make every voice count.</h1><p>Launch live polls and Q&A your audience can join in seconds.</p></div><Link className="button" to="/create">+ Create New Poll</Link></section>{loading?<Loading/>:polls.length===0?<div className="empty"><div className="empty-icon">✦</div><h2>Your stage is ready</h2><p>Create your first poll, share the QR code, and watch the room come alive.</p><Link className="button" to="/create">Create New Poll</Link></div>:<div className="grid">{polls.map(p=><Link className="poll-card" to={`/poll/${p.id}`} key={p.id}><div className="card-top"><Badge status={p.status}/><span>{p.type==='choice'?'Multiple choice':'Q&A'}</span></div><h2>{p.title}</h2><p>{p.question}</p><footer><b>{counts[p.id]??0}</b> {p.type==='choice'?'responses':'questions'} <span>Manage →</span></footer></Link>)}</div>}</Shell> }

function Create(){const nav=useNavigate();const [title,setTitle]=useState('');const [question,setQuestion]=useState('');const [type,setType]=useState<PollType>('choice');const [opts,setOpts]=useState(['','']);const [busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!title.trim()||!question.trim()|| (type==='choice'&&opts.some(x=>!x.trim())))return;setBusy(true);const {data,error}=await supabase.from('polls').insert({title,question,type,status:'draft'}).select().single();if(error||!data){alert(error?.message??'Could not create poll');setBusy(false);return}if(type==='choice')await supabase.from('options').insert(opts.map((option_text,display_order)=>({poll_id:data.id,option_text,display_order})));nav(`/poll/${data.id}`)};return <Shell><div className="form-wrap"><p className="eyebrow">NEW SESSION</p><h1>Create a poll</h1><form onSubmit={submit} className="form-card"><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Team all-hands"/></label><label>Question<textarea required value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What would you like to ask the room?"/></label><fieldset><legend>Format</legend><div className="type-row"><button type="button" className={type==='choice'?'selected':''} onClick={()=>setType('choice')}>☷ <b>Multiple Choice</b><small>Let people pick an answer</small></button><button type="button" className={type==='qa'?'selected':''} onClick={()=>setType('qa')}>✦ <b>Q&A</b><small>Collect and rank questions</small></button></div></fieldset>{type==='choice'&&<div className="options"><label>Answer options</label>{opts.map((o,i)=><div className="option-input" key={i}><span>{i+1}</span><input required value={o} onChange={e=>setOpts(opts.map((x,n)=>n===i?e.target.value:x))} placeholder={`Option ${i+1}`}/>{i>1&&<button type="button" onClick={()=>setOpts(opts.filter((_,n)=>n!==i))}>×</button>}</div>)}{opts.length<6&&<button type="button" className="text-button" onClick={()=>setOpts([...opts,''])}>+ Add option</button>}</div>}<div className="form-actions"><Link to="/">Cancel</Link><button className="button" disabled={busy}>{busy?'Creating…':'Create draft'}</button></div></form></div></Shell>}

function Results({type,options,votes,questions,large=false}:{type:PollType;options:Option[];votes:Vote[];questions:Question[];large?:boolean}){if(type==='qa')return <div className={`qa-list ${large?'large':''}`}>{questions.length===0?<p className="muted">Questions from the audience will appear here.</p>:questions.map((q,i)=><article key={q.id}><span className="rank">{i+1}</span><p>{q.question_text}</p><b>↑ {q.upvotes}</b></article>)}</div>;const total=votes.length;return <div className={`bars ${large?'large':''}`}>{options.map((o,i)=>{const count=votes.filter(v=>v.option_id===o.id).length;const pct=total?Math.round(count/total*100):0;return <div className="bar" key={o.id}><div className="bar-label"><span><i style={{background:colors[i]}} />{o.option_text}</span><b>{pct}% <small>{count}</small></b></div><div className="track"><div style={{width:`${pct}%`,background:colors[i]}} /></div></div>})}</div>}

function PollManage(){const {id=''}=useParams();const {poll,options,votes,questions,loading}=usePoll(id);const nav=useNavigate();const link=`${window.location.origin}/vote/${id}`;const setStatus=async(status:Status)=>await supabase.from('polls').update({status}).eq('id',id);const reset=async()=>{if(confirm('Clear all responses? This cannot be undone.')){await Promise.all([supabase.from('votes').delete().eq('poll_id',id),supabase.from('questions').delete().eq('poll_id',id)])}};if(loading)return <Shell><Loading/></Shell>;if(!poll)return <Shell><div className="state">Poll not found.</div></Shell>;return <Shell><section className="manage-head"><div><Link to="/" className="back">← All polls</Link><div className="title-row"><h1>{poll.title}</h1><Badge status={poll.status}/></div><p>{poll.question}</p></div><button className="button secondary" onClick={()=>nav(`/poll/${id}/present`)}>Present ↗</button></section><div className="manage-grid"><aside className="join-card"><p className="eyebrow">AUDIENCE JOIN</p><div className="qr"><QRCodeSVG value={link} size={190} bgColor="#ffffff" fgColor="#17142b"/></div><p className="join-url">{link}</p><button className="copy" onClick={()=>navigator.clipboard.writeText(link)}>Copy link</button></aside><section className="control-card"><p className="eyebrow">SESSION CONTROLS</p><h2>{poll.status==='live'?'Voting is open':'Ready when you are'}</h2><p>{poll.status==='live'?'Responses are appearing live for everyone.':'Open the poll when you want the audience to participate.'}</p><div className="controls">{poll.status!=='live'?<button className="button" onClick={()=>setStatus('live')}>Open voting</button>:<button className="button danger" onClick={()=>setStatus('closed')}>Close voting</button>}<button className="text-button" onClick={reset}>Reset results</button></div></section></div><section className="results-card"><div className="results-head"><div><p className="eyebrow">LIVE RESULTS</p><h2>{poll.type==='choice'?`${votes.length} responses`:`${questions.length} audience questions`}</h2></div></div><Results type={poll.type} options={options} votes={votes} questions={questions}/></section></Shell>}

function Present(){const {id=''}=useParams();const {poll,options,votes,questions,loading}=usePoll(id);const link=`${window.location.origin}/vote/${id}`;if(loading)return <div className="present"><Loading/></div>;if(!poll)return <div className="present"><div className="state">Poll not found.</div></div>;return <div className="present"><div className="present-top"><span className="present-brand">◉ PulseLive</span><Badge status={poll.status}/></div><div className="present-body"><p className="eyebrow">{poll.title}</p><h1>{poll.question}</h1><Results type={poll.type} options={options} votes={votes} questions={questions} large/></div><div className="present-qr"><QRCodeSVG value={link} size={118}/><span>Scan to join</span></div></div>}

function Vote(){const {id=''}=useParams();const {poll,options,votes,questions,loading}=usePoll(id);const [done,setDone]=useState(false);const [text,setText]=useState('');const [sending,setSending]=useState(false);const vote=async(option_id:string)=>{setSending(true);const {error}=await supabase.from('votes').insert({poll_id:id,option_id});if(error)alert(error.message);else setDone(true);setSending(false)};const ask=async(e:React.FormEvent)=>{e.preventDefault();if(!text.trim())return;setSending(true);const {error}=await supabase.from('questions').insert({poll_id:id,question_text:text.trim(),upvotes:0});if(error)alert(error.message);else setText('');setSending(false)};const upvote=async(q:Question)=>await supabase.from('questions').update({upvotes:q.upvotes+1}).eq('id',q.id);if(loading)return <div className="audience"><Loading/></div>;if(!poll)return <div className="audience"><div className="state">This poll could not be found.</div></div>;return <div className="audience"><div className="audience-inner"><div className="audience-brand">◉ PulseLive</div><p className="eyebrow">{poll.type==='choice'?'LIVE POLL':'LIVE Q&A'}</p><h1>{poll.question}</h1>{poll.status!=='live'?<div className="closed"><span>◷</span><h2>This poll isn't open for responses right now.</h2><p>Keep this page open — the presenter may start it soon.</p></div>:poll.type==='choice'?<>{done?<div className="thanks"><span>✓</span><h2>Thanks for voting!</h2><p>Your response has been counted.</p></div>:<div className="vote-options">{options.map((o,i)=><button disabled={sending} onClick={()=>vote(o.id)} key={o.id}><i style={{background:colors[i]}}/>{o.option_text}<b>→</b></button>)}</div>}<div className="audience-results"><p>LIVE RESULTS</p><Results type="choice" options={options} votes={votes} questions={[]}/></div></>:<><form className="ask" onSubmit={ask}><textarea value={text} maxLength={280} onChange={e=>setText(e.target.value)} placeholder="Ask a question…"/><button className="button" disabled={sending}>{sending?'Sending…':'Submit question'}</button></form><div className="audience-questions">{questions.map(q=><article key={q.id}><p>{q.question_text}</p><button onClick={()=>upvote(q)}>↑ {q.upvotes}</button></article>)}{questions.length===0&&<p className="muted">Be the first to ask a question.</p>}</div></>}</div></div>}

function App(){return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/create" element={<Create/>}/><Route path="/poll/:id" element={<PollManage/>}/><Route path="/poll/:id/present" element={<Present/>}/><Route path="/vote/:id" element={<Vote/>}/><Route path="*" element={<Dashboard/>}/></Routes>}
export default App
